installCRDs: false
dex:
  enabled: false
server:
  ingress: 
    enabled: true
    hosts:
      - blah
  config:
    url: blah
    repositories: |
      - url: https://github.com/cldmnky/cluster-bootstrap.git
        passwordSecret:
          name: bootstrap
          key: password
        usernameSecret:
          name: bootstrap
          key: username
  additionalApplications:
    - name: bootstrap
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/cldmnky/cluster-bootstrap.git
        targetRevision: master
        path: bootstrap
        helm:
          values: |-  
            cluster: foo-stage-cluster
            environment: stage
            spec:
              destination:
                server: https://kubernetes.default.svc
              source:
                repoURL: https://github.com/cldmnky/cluster-bootstrap.git
                targetRevision: master 
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
        syncPolicy:
          automated:
            prune: true
          selfHeal: false
repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
 
  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
      - apk add curl &&
        wget -qO- https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz | tar -xvzf - &&
        mv linux-amd64/helm /custom-tools/helm-v3 &&
        wget -qO- https://get.helm.sh/helm-v2.16.1-linux-amd64.tar.gz | tar -xvzf - &&
        mv linux-amd64/helm /custom-tools/helm-v2 &&
        curl https://gist.githubusercontent.com/cldmnky/da87b8d555c951251b503c668dab2248/raw/6e6f8e302ff1116300877f294f08f97b9cf495ac/helm-wrapper.sh > /custom-tools/helm &&
        chmod 777 /custom-tools/helm
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/helm-v2
    name: custom-tools
    subPath: helm-v2
  - mountPath: /usr/local/bin/helm-v3
    name: custom-tools
    subPath: helm-v3
  - mountPath: /usr/local/bin/helm
    name: custom-tools
    subPath: helm
